### PR TITLE
Feature/disable npm runtime error

### PR DESCRIPTION
**Pull request by metalwarrior665**
Adding extra `env` to each apify.json. 

The Dockerfiles CMDs fallback to parent image CMD so we don't need to update it here. I made also PR to our main Dockerfiles.

### CODE REVIEW

**Comment by pocesar** [comment]
locally, it will work just as it would on the platform. since the local SDK doesn't use Docker images, I think that's fine

**Comment by jancurn** [comment]
@pocesar oh right, fair enough

**Comment by mnmkng** [comment]
So the point of this is to get rid of the NPM error on local? I don't know, it's weird. First of all, it will only work when using `apify-cli` and second, it injects some env vars into the system from a very unexpected place.

**Comment by metalwarrior665** [comment]
Yes, that's the point. To save terminal space and also the error is confusing for Node beginners.

CLI is injecting many env vars too.

**Comment by metalwarrior665** [comment]
But if you think it would be better to do it from another place (directly from the CLI), then I'm all for it. It is a cosmetic thing ofc, nothing too serious.

**Comment by mnmkng** [comment]
You know what, I'll just merge it because it's better than the current situation and we can figure out a better way later.

**Pull request merged**
